default_context:
    full_name: "Harro Hatchelorette"
    email: "harro@Hatchelorette.com"
    github_username: "Hatchelorette"
    project_name: "Hatchelorette demo project"
    project_slug: "hatchelorette-demo"
    project_short_description: "Python project featuring the Python project manager hatch powerd by the Hatchelorette."
    open_source_license: "proprietary"
    target_python_version: "3.10"
    project_repo: "https://github.com/FlorianWilhelm/the-hatchelorette-demo"
    pypi_username: "{{ cookiecutter.github_username }}"
    lock_file_support: false
    